import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


const ageo = localFont({
  src: [
    {
      path: '../../public/font/Akrobat.otf',
      //path: '../../public/font/BebasNeue-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/font/Akrobat-Bold.otf',
      weight: '700',
      style: 'bold',
    },
    {
      path: '../../public/font/Akrobat-ExtraBold.otf',
      weight: '850',
      style: 'extra-bold',
    },
    {
      path: '../../public/font/Akrobat-Medium.otf',
      weight: '500',
      style: 'medium',
    },
  ],
})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (   
    <html lang="en">
      <body  className={ageo.className}>{children}</body>
    </html>
  )
}
